import type { DomainErrorCode } from "@/lib/video-metadata/contracts";

const DOMAIN_ERROR_STATUS = {
  validation_failed: 400,
  unauthorized: 401,
  AUTH_CALLBACK_INVALID: 401,
  AUTH_REFRESH_TOKEN_MISSING: 401,
  AUTH_USER_NOT_FOUND: 401,
  AUTH_SCOPE_INSUFFICIENT: 403,
  not_found: 404,
  target_language_unresolvable: 422,
  transcript_unavailable: 422,
  generation_failed: 422,
  update_failed: 422,
  WRITE_CHANNEL_REQUIRED: 422,
  WRITE_CHANNEL_UNRESOLVED: 422,
  WRITE_CHANNEL_MISMATCH: 409,
  CHANNEL_NOT_ACTIVE: 403,
  change_not_approvable: 409,
  batch_invalid_selection: 400,
  batch_not_found: 404,
  batch_already_running: 409,
  ledger_row_not_found: 404,
  ledger_invalid_transition: 409,
  video_locked: 409,
  attempt_already_resolved: 409,
  attempt_already_active: 409,
  change_approval_invalid: 409,
  default_language_missing: 422,
  backup_item_failed: 422,
  backup_infrastructure_unavailable: 503,
  live_writes_disabled: 503,
  provider_not_configured: 501,
  generation_invalid_target_language: 422,
  generation_no_proposals: 422,
  encryption_key_not_configured: 503,
  capability_not_supported: 422,
  endpoint_not_allowed: 422,
  connection_disabled: 409,
  no_fields_to_update: 400,
  publish_at_requires_private: 400,
  publish_at_already_published: 409,
  video_details_conflict: 409,
  deletion_targets_default_language: 422,
  divergent_document_lineage: 409,
  crdt_conflict_open: 409,
} as const satisfies Partial<Record<DomainErrorCode, number>>;

export function getVideoMetadataErrorStatus(code: DomainErrorCode) {
  return DOMAIN_ERROR_STATUS[code] ?? 422;
}
